"""create shelf_shares table

Revision ID: 8d0f63c45932
Revises: 0345aca62cb0
Create Date: 2026-08-19 11:42:00.686495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0f63c45932'
down_revision: Union[str, Sequence[str], None] = '0345aca62cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelf_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelf_shares_id'), 'shelf_shares', ['id'], unique=False)
    op.create_index(op.f('ix_shelf_shares_shelf_id'), 'shelf_shares', ['shelf_id'], unique=False)
    op.create_index(op.f('ix_shelf_shares_user_id'), 'shelf_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shelf_shares_user_id'), table_name='shelf_shares')
    op.drop_index(op.f('ix_shelf_shares_shelf_id'), table_name='shelf_shares')
    op.drop_index(op.f('ix_shelf_shares_id'), table_name='shelf_shares')
    op.drop_table('shelf_shares')
    # ### end Alembic commands ###
