"""create shelves and shelf_books tables

Revision ID: 0345aca62cb0
Revises: f3020701552a
Create Date: 2026-08-19 10:52:16.674684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0345aca62cb0'
down_revision: Union[str, Sequence[str], None] = 'f3020701552a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelves_id'), 'shelves', ['id'], unique=False)
    op.create_index(op.f('ix_shelves_owner_id'), 'shelves', ['owner_id'], unique=False)
    op.create_table('shelf_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelf_books_book_id'), 'shelf_books', ['book_id'], unique=False)
    op.create_index(op.f('ix_shelf_books_id'), 'shelf_books', ['id'], unique=False)
    op.create_index(op.f('ix_shelf_books_shelf_id'), 'shelf_books', ['shelf_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shelf_books_shelf_id'), table_name='shelf_books')
    op.drop_index(op.f('ix_shelf_books_id'), table_name='shelf_books')
    op.drop_index(op.f('ix_shelf_books_book_id'), table_name='shelf_books')
    op.drop_table('shelf_books')
    op.drop_index(op.f('ix_shelves_owner_id'), table_name='shelves')
    op.drop_index(op.f('ix_shelves_id'), table_name='shelves')
    op.drop_table('shelves')
    # ### end Alembic commands ###
